---
name: Data-Generate
version: 0.02
author:
  - 'Davide Conti <daconti.mail@gmail.com>'
abstract: Generate data arrays by parsing user statements
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Date::DayOfWeek: 0
  Date::Parse: 0
  Parse::RecDescent: 1.94
  Test::More: 0.47
  perl: 0.005
provides:
  Data::Generate:
    file: lib/Data/Generate.pm
    version: 0.02
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
