---
name: Data-Generate
version: 0.01
author:
  - 'Davide Conti <daconti.mail@gmail.com>'
abstract: Generate data arrays by parsing user statements
license: artistic
requires:
  Date::DayOfWeek: 0
  Date::Parse: 0
  Parse::RecDescent: 1.94
  Test::More: 0.47
  perl: 0.005
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Data::Generate:
    file: lib/Data/Generate.pm
    version: 0.01
resources:
  license: http://opensource.org/licenses/artistic-license.php
